kind: pipeline
type: docker
name: make test

clone:
  skip_verify: true

platform:
  os: linux
  arch: amd64

environment:
  GO111MODULE: on
  GOPROXY: https://goproxy.cn,direct

steps:
- name: check
  image: golang:1.21.0
  commands:
  - make setup
  - make check

- name: test
  image: golang:1.21.0
  commands:
  - go test -v ./...

- name: build
  image: golang:1.21.0
  commands:
  - go build -v ./...

trigger:
  branch:
    - main
    - develop
    - feature/*
    - fix/*
  event:
    - push
    - pull_request

---
kind: pipeline
type: docker
name: build and deploy

clone:
  skip_verify: true

steps:
- name: docker-build
  image: plugins/docker
  settings:
    force_tag: true
    insecure: true
    registry: docker.registry.bawcat.wiki
    repo: docker.registry.bawcat.wiki/ogreks/meeseeks-box
    username:
      from_secret: docker_username
    password:
      from_secret: docker_passwd
    debug: true

- name: deploy
  image: appleboy/drone-ssh
  settings:
    host:
      from_secret: meeseeks_box_host
    user:
      from_secret: meeseeks_box_user
    password:
      from_secret: meeseeks_box_passwd
    script:
      - docker pull docker.registry.bawcat.wiki/ogreks/meeseeks-box:latest
      - docker stop meeseeks-box
      - docker rm meeseeks-box
      - docker run -d --name meeseeks-box -p 8088:8088 -v /data/meeseeks-box/config.yml:/etc/meeseeks-box/config.yml --privileged=true docker.registry.bawcat.wiki/ogreks/meeseeks-box:latest
      - docker image prune -a -f # 删除无用的老版本

depends_on:
  - make test

trigger:
  branch:
    - develop
  event:
    - promote
    - rollback