kind: pipeline
type: docker
name: default

clone:
  skip_verify: true

platform:
  os: linux
  arch: amd64

environment:
  GO111MODULE: on
  GOPROXY: https://goproxy.cn,direct

steps:
- name: check
  image: golang:1.21.0
  commands:
  - make check

- name: test
  image: golang:1.21.0
  commands:
  - go test -v ./...

- name: build
  image: golang:1.21.0
  commands:
  - go build -v ./...

trigger:
  branch:
    - main
    - develop
  event:
    - push
    - pull_request