kind: pipeline
type: docker
name: default

clone:
  skip_verify: true

steps:
- name: check
  image: golang:1.21.0
  commands:
  - make check

- name: test
  image: golang:1.21.0
  commands:
  - go test -v ./...

- name: build
  image: golang:1.21.0
  commands:
  - go build -v ./...