// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSessionKey = "session_keys"

// SessionKey 交互秘钥表
type SessionKey struct {
	ID        int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	SessionNo string     `gorm:"column:session_no;type:varchar(32);not null;uniqueIndex:unx_session_no,priority:1;comment:交互秘钥唯一标识" json:"session_no"`               // 交互秘钥唯一标识
	Name      string     `gorm:"column:name;type:varchar(64);not null;index:idx_name,priority:1;comment:用途名称" json:"name"`                                           // 用途名称
	Type      uint32     `gorm:"column:type;type:tinyint unsigned;not null;comment:密钥权限类型 1. 主程API / 2.管理API / 3.服务API" json:"type"`                                 // 密钥权限类型 1. 主程API / 2.管理API / 3.服务API
	AppID     string     `gorm:"column:app_id;type:char(8);not null;index:idx_app_id,priority:1;comment:客户端appid-自动生成" json:"app_id"`                                // 客户端appid-自动生成
	AppSecret string     `gorm:"column:app_secret;type:char(40);not null;comment:客户端秘钥自动生成，加密存储" json:"app_secret"`                                                  // 客户端秘钥自动生成，加密存储
	IsEnabled uint32     `gorm:"column:is_enabled;type:tinyint unsigned;not null;comment:是否启用 0.停用 / 1.启用" json:"is_enabled"`                                        // 是否启用 0.停用 / 1.启用
	Remark    string     `gorm:"column:remark;type:text;comment:备注" json:"remark"`                                                                                   // 备注
	CreatedAt *time.Time `gorm:"column:created_at;type:timestamp;not null;index:idx_created_at,priority:1;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt *time.Time `gorm:"column:updated_at;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`                                 // 更新时间
	DeletedAt *time.Time `gorm:"column:deleted_at;type:timestamp" json:"deleted_at"`
}

// TableName SessionKey's table name
func (*SessionKey) TableName() string {
	return TableNameSessionKey
}
