// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserSignature = "user_signatures"

// UserSignature 用户签署表
type UserSignature struct {
	ID          int64      `gorm:"column:id;type:bigint;primaryKey" json:"id"`
	Type        int32      `gorm:"column:type;type:int;not null;comment:签署类型" json:"type"`                                                                 // 签署类型
	UserID      int64      `gorm:"column:user_id;type:bigint;not null;index:idx_user_id,priority:1;comment:用户id" json:"user_id"`                           // 用户id
	AccountID   int64      `gorm:"column:account_id;type:bigint;not null;index:idx_account_id,priority:1;comment:账号id" json:"account_id"`                  // 账号id
	AccountAid  string     `gorm:"column:account_aid;type:varchar(32);not null;index:idx_account_aid,priority:1;comment:账号aid" json:"account_aid"`         // 账号aid
	AgreementID int64      `gorm:"column:agreement_id;type:bigint;not null;index:idx_agreement_id,priority:1;comment:协议id" json:"agreement_id"`            // 协议id
	AgreementNo string     `gorm:"column:agreement_no;type:varchar(32);not null;index:idx_agreement_no,priority:1;comment:协议编号" json:"agreement_no"`       // 协议编号
	Signed      bool       `gorm:"column:signed;type:tinyint(1);not null;comment:是否已签署 0 否 1是" json:"signed"`                                              // 是否已签署 0 否 1是
	SignedAt    *time.Time `gorm:"column:signed_at;type:timestamp;index:idx_signed_at,priority:1;comment:签署时间" json:"signed_at"`                           // 签署时间
	CreatedAt   *time.Time `gorm:"column:created_at;type:timestamp;not null;index:idx_created_at,priority:1;default:now();comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt   *time.Time `gorm:"column:updated_at;type:timestamp;not null;default:now();comment:更新时间" json:"updated_at"`                                 // 更新时间
	DeletedAt   *time.Time `gorm:"column:deleted_at;type:timestamp" json:"deleted_at"`
}

// TableName UserSignature's table name
func (*UserSignature) TableName() string {
	return TableNameUserSignature
}
